image:
  file: .gitpod.Dockerfile

# Define services
tasks:
  - name: web
    before: pip install --no-cache-dir -r requirements.txt
    init: npm i -D playwright && npx playwright install
    command: daphne chatbackend.asgi:application -b 0.0.0.0 -p 8000

  - name: celery
    command: celery -A chatbackend worker --loglevel=info

ports:
  - port: 8000
    onOpen: open-preview

# Services similar to docker-compose services
services:
  - name: redis
    image: redis:latest
    ports:
      - port: 6379
